# try and exception
a= 'a'
try:
  b= int(a)
  print(b)
except:
  print(a)

print('test')

